{% set name = "aiida-gromacs" %}
{% set version = "2.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: python -m pip install . -vv
      entry_points:
        - gmx_pdb2gmx=aiida_gromacs.cli.pdb2gmx:cli
        - gmx_editconf=aiida_gromacs.cli.editconf:cli
        - gmx_genion=aiida_gromacs.cli.genion:cli
        - gmx_grompp=aiida_gromacs.cli.grompp:cli
        - gmx_mdrun=aiida_gromacs.cli.mdrun:cli
        - gmx_solvate=aiida_gromacs.cli.solvate:cli
        - gmx_make_ndx=aiida_gromacs.cli.make_ndx:cli
        - genericMD=aiida_gromacs.cli.genericMD:cli
        - createarchive=aiida_gromacs.cli.createarchive:cli
    requirements:
      host:
        - python
        - pip
        - flit-core >=3.4,<4
      run:
        - python
        - aiida-core >=2.6.1,<=2.6.3
        - voluptuous
    about:
      home: https://github.com/CCPBioSim/aiida-gromacs
      license: MIT
      license_file: LICENSE
      summary: A plugin for using GROMACS with AiiDA for molecular dymanics simulations.

test:
  imports:
    - aiida_gromacs
  commands:
    - gmx_grompp --help
    - gmx_mdrun --help
    - python -c "import aiida_gromacs; print(aiida_gromacs.__version__)"
